#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

curdir := $(shell pwd)

# compile C with /usr/bin/cc
C_FLAGS = -g   -Wall -Wno-unknown-pragmas -Wno-undef -Wno-long-long -Wfloat-equal -Wpointer-arith -Wlogical-op -std=c99

C_DEFINES = -DASIO_STANDALONE -DHCI_LINK_CONTROL -DNRF_SD_BLE_API=6 -DSD_RPC_EXPORTS

C_INCLUDES = -I$(curdir)/../include/sd_api_v6 -I$(curdir)/../include/common/config -I$(curdir)/../include/common/sdk_compat -I$(curdir)/../include/common

examples/collector.c.o: ../examples/heart_rate_collector/main.c
	cd $(curdir)/examples && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o collector.c.o   -c $(curdir)/../examples/heart_rate_collector/main.c

# Rule to build all files generated by this target.
build: examples/collector.c.o

.PHONY : build
