objdir=objects

libnrf-ble-driver-sd_api_v6.a: $(objdir)/app_ble_user_mem.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_event.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_evt_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gap_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gap_evt_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gattc_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gattc_evt_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gatts_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gatts_evt_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_l2cap_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_l2cap_evt_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/conn_systemreset_app.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/cond_field_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gap_struct_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gattc_struct_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gatts_struct_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gatt_struct_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_l2cap_struct_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_struct_serialization.c.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/adapter_internal.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/app_ble_gap.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_common.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/sd_rpc_impl.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gap_impl.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gattc_impl.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_gatts_impl.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/ble_impl.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/h5.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/h5_transport.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/serialization_transport.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/slip.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/transport.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/uart_settings.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/uart_settings_boost.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/uart_transport.cpp.o
libnrf-ble-driver-sd_api_v6.a: $(objdir)/serial_port_enum.cpp.o

# Rule to build all files generated by this target.
build: libnrf-ble-driver-sd_api_v6.a
	cd $(objdir) && \
	/usr/bin/ar qc libnrf-ble-driver-sd_api_v6.a \
	app_ble_user_mem.c.o \
	ble_app.c.o \
	ble_event.c.o \
	ble_evt_app.c.o \
	ble_gap_app.c.o \
	ble_gap_evt_app.c.o \
	ble_gattc_app.c.o \
	ble_gattc_evt_app.c.o \
	ble_gatts_app.c.o \
	ble_gatts_evt_app.c.o \
	ble_l2cap_app.c.o \
	ble_l2cap_evt_app.c.o \
	conn_systemreset_app.c.o \
	ble_serialization.c.o \
	cond_field_serialization.c.o \
	ble_gap_struct_serialization.c.o \
	ble_gattc_struct_serialization.c.o \
	ble_gatts_struct_serialization.c.o \
	ble_gatt_struct_serialization.c.o \
	ble_l2cap_struct_serialization.c.o \
	ble_struct_serialization.c.o \
	adapter_internal.cpp.o \
	app_ble_gap.cpp.o \
	ble_common.cpp.o \
	sd_rpc_impl.cpp.o \
	ble_gap_impl.cpp.o \
	ble_gattc_impl.cpp.o \
	ble_gatts_impl.cpp.o \
	ble_impl.cpp.o \
	h5.cpp.o \
	h5_transport.cpp.o \
	serialization_transport.cpp.o \
	slip.cpp.o \
	transport.cpp.o \
	uart_settings.cpp.o \
	uart_settings_boost.cpp.o \
	uart_transport.cpp.o \
	serial_port_enum.cpp.o && \
	/usr/bin/ranlib libnrf-ble-driver-sd_api_v6.a

.PHONY : build
